spring:
  application:
    name: falaidoutor
  ai:
    ollama:
      chat:
#        model: deepseek-r1:1.5b
        model: dolphin-llama3
  datasource:
    url: jdbc:postgresql://localhost:5432/falaidoutor
    username: postgres
    password: 1206
    driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5433/falaidoutor
#      username: postgres
#      password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: falaidoutor