spring:
  application:
    name: falaidoutor
  ai:
    ollama:
      chat:
        model: dolphin-llama3
  datasource:
      url: jdbc:postgresql://localhost:5432/falaidoutor
      username: ${secrets.db-username}
      password: ${secrets.db-password}
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: falaidoutor